/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DriverToolsGUI.java
 *
 * Created on 21-Mar-2012, 18:54:13
 */

package ibms.gui;

import ibms.exceptions.NotEnoughHolidaysException;
import ibms.exceptions.UnknownDriverException;
import ibms.models.Driver;
import ibms.models.Holiday;
import ibms.models.RestDay;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

/**
 *
 * @author nunnerp0
 */
public class DriverToolsGUI extends javax.swing.JFrame {
    Driver currentDriver;
     /** Creates new form DriverToolsGUI */
    public DriverToolsGUI() {
        initComponents();
        pnlHoliday.setVisible(false);
        this.pnlRestDay.setVisible(false);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHoliday = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtHolidaysTaken = new javax.swing.JTextField();
        pnlBook = new javax.swing.JPanel();
        lblStartDate = new javax.swing.JLabel();
        lblEndDate = new javax.swing.JLabel();
        btnBook = new javax.swing.JButton();
        txtStartDate = new javax.swing.JTextField();
        txtEndDate = new javax.swing.JTextField();
        pnlRestDay = new javax.swing.JPanel();
        lblFirstDay = new javax.swing.JLabel();
        txtFirstDay = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtDriverId = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        lblDriverId = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();

        setTitle("Driver Tools");

        pnlHoliday.setBorder(javax.swing.BorderFactory.createTitledBorder("Holidays"));
        pnlHoliday.setOpaque(false);

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Drivers are entitled to 25 holidays in a year. Here you can see how many holiday you have currently booked and where appropriate book days off where you don't wish to work.");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setText("No of days left you could book off:");

        txtHolidaysTaken.setEditable(false);
        txtHolidaysTaken.setText("25");
        txtHolidaysTaken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHolidaysTakenActionPerformed(evt);
            }
        });

        pnlBook.setBorder(javax.swing.BorderFactory.createTitledBorder("Book a holiday"));

        lblStartDate.setLabelFor(txtStartDate);
        lblStartDate.setText("Start Date");

        lblEndDate.setLabelFor(txtEndDate);
        lblEndDate.setText("End Date");

        btnBook.setText("Book");
        btnBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBookMouseClicked(evt);
            }
        });

        txtStartDate.setText("dd-mm-yyyy");

        txtEndDate.setText("dd-mm-yyyy");

        javax.swing.GroupLayout pnlBookLayout = new javax.swing.GroupLayout(pnlBook);
        pnlBook.setLayout(pnlBookLayout);
        pnlBookLayout.setHorizontalGroup(
            pnlBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBookLayout.createSequentialGroup()
                .addGroup(pnlBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBookLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStartDate)
                            .addComponent(lblEndDate))
                        .addGap(132, 132, 132)
                        .addGroup(pnlBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtEndDate)
                            .addComponent(txtStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)))
                    .addGroup(pnlBookLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(btnBook)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        pnlBookLayout.setVerticalGroup(
            pnlBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBookLayout.createSequentialGroup()
                .addGroup(pnlBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStartDate)
                    .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndDate)
                    .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBook))
        );

        pnlRestDay.setBorder(javax.swing.BorderFactory.createTitledBorder("Define Rest Day"));

        lblFirstDay.setText("Rest Day:");

        txtFirstDay.setText("dd-mm-yyyy");
        txtFirstDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstDayActionPerformed(evt);
            }
        });

        jButton1.setText("Define");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlRestDayLayout = new javax.swing.GroupLayout(pnlRestDay);
        pnlRestDay.setLayout(pnlRestDayLayout);
        pnlRestDayLayout.setHorizontalGroup(
            pnlRestDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRestDayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFirstDay, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(txtFirstDay, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(pnlRestDayLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jButton1)
                .addContainerGap(219, Short.MAX_VALUE))
        );
        pnlRestDayLayout.setVerticalGroup(
            pnlRestDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRestDayLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnlRestDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstDay)
                    .addComponent(txtFirstDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlHolidayLayout = new javax.swing.GroupLayout(pnlHoliday);
        pnlHoliday.setLayout(pnlHolidayLayout);
        pnlHolidayLayout.setHorizontalGroup(
            pnlHolidayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHolidayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHolidayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlRestDay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBook, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlHolidayLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                        .addComponent(txtHolidaysTaken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlHolidayLayout.setVerticalGroup(
            pnlHolidayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHolidayLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHolidayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHolidaysTaken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(pnlBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlRestDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtDriverId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDriverIdActionPerformed(evt);
            }
        });

        btnLogin.setText("Login");
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblDriverId.setText("Enter Driver Number:");

        lblError.setFont(new java.awt.Font("Ubuntu", 1, 14));
        lblError.setText("No driver selected.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDriverId)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(txtDriverId, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btnLogin)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 268, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlHoliday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDriverId)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDriverId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlHoliday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHolidaysTakenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHolidaysTakenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHolidaysTakenActionPerformed

    private void txtDriverIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDriverIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDriverIdActionPerformed

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        // TODO add your handling code here:
        try{
            String driverNumber = this.txtDriverId.getText();
            currentDriver = new Driver(driverNumber);
            this.lblError.setText(currentDriver.getName() + "(" + currentDriver.getNumber() + ")");
            this.pnlHoliday.setVisible(true);
            this.pnlRestDay.setVisible(true);
            //set the number of holidays taken based on current driver
            this.txtHolidaysTaken.setText(currentDriver.holidaysAvailable() + "");
        }
        catch(UnknownDriverException e){
            this.lblError.setText("Can't find that driver");
            this.pnlHoliday.setVisible(false);
            this.pnlRestDay.setVisible(false);
            
        }catch(Exception e){
            this.lblError.setText("Couldn't find that driver");
        }
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookMouseClicked
        // TODO add your handling code here:
        SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy");
        try{
            Calendar start = GregorianCalendar.getInstance();
            start.setTime(format.parse(txtStartDate.getText()));
            Calendar end = GregorianCalendar.getInstance();
            end.setTime(format.parse(txtEndDate.getText()));
            
            try{
                Holiday newHoliday = new Holiday(currentDriver.getNumber(), start, end);
                this.lblError.setText("Holiday added");
                this.txtHolidaysTaken.setText("" + this.currentDriver.holidaysAvailable());

            }
            catch(NotEnoughHolidaysException e){
                this.lblError.setText("You don't have enough holidays available for that booking");
            }
            catch(Exception e){
                System.out.println("" + e);
            }
        }catch(Exception e){
            System.out.println(e);
        }

    }//GEN-LAST:event_btnBookMouseClicked

    private void txtFirstDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstDayActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        try{
            Calendar first = new GregorianCalendar();
            first.setTime(formatter.parse(this.txtFirstDay.getText()));
            RestDay newRestDay = new RestDay(currentDriver.getNumber(), first);
        }catch(DateTakenException e){
            this.lblError.setText("You're already inavilable on the date you selected.")
        }catch(Exception e){
            System.err.println(e);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DriverToolsGUI().setVisible(true);
            }
        });
    }

    public void setDaysTaken(int daysTaken)
    {
        txtHolidaysTaken.setText("" + daysTaken);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblDriverId;
    private javax.swing.JLabel lblEndDate;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblFirstDay;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JPanel pnlBook;
    private javax.swing.JPanel pnlHoliday;
    private javax.swing.JPanel pnlRestDay;
    private javax.swing.JTextField txtDriverId;
    private javax.swing.JTextField txtEndDate;
    private javax.swing.JTextField txtFirstDay;
    private javax.swing.JTextField txtHolidaysTaken;
    private javax.swing.JTextField txtStartDate;
    // End of variables declaration//GEN-END:variables

}
