/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PassengerToolsGUI.java
 *
 * Created on 10-May-2012, 11:53:14
 */

package ibms.gui;
import ibms.wrappers.*;
/**
 *
 * @author malikze0
 */
public class PassengerToolsGUI extends javax.swing.JFrame {

    /** Creates new form PassengerToolsGUI */
    public PassengerToolsGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        StartArea_ComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        StartStop_ComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        End_ComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        endStop_ComboBox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Start Point Area:");

        StartArea_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        StartArea_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartArea_ComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Start Point Bus Stop:");

        StartStop_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("End Point Area:");

        End_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        End_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                End_ComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setText("End Point Bus Stop:");

        endStop_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("jButton1");

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(StartArea_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(End_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(endStop_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StartStop_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jButton1)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StartArea_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StartStop_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(End_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endStop_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartArea_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartArea_ComboBoxActionPerformed
        // TODO add your handling code here:        
        if(!created)            
            setAreas();
        created = true;
        setBusStops();
    }//GEN-LAST:event_StartArea_ComboBoxActionPerformed

    private void End_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_End_ComboBoxActionPerformed
        // TODO add your handling code here:
        if(!created)
            setAreas();
        created = true;
        setBusStops();
    }//GEN-LAST:event_End_ComboBoxActionPerformed

    /**
    * @param args the command line arguments
    */
    public void setAreas()
    {        
        StartArea_ComboBox.removeAllItems();
        End_ComboBox.removeAllItems();
        
        int[] areas = BusStopInfo.getAreas();

        for(int i=0; i<areas.length; i++)
        {
            StartArea_ComboBox.addItem(BusStopInfo.getAreaName(areas[i]));
            End_ComboBox.addItem(BusStopInfo.getAreaName(areas[i]));
        }
        setBusStops();
    }

    public void setBusStops()
    {
        StartStop_ComboBox.removeAllItems();
        endStop_ComboBox.removeAllItems();
        String areaName = StartArea_ComboBox.getSelectedItem().toString();
        int startAreaId = BusStopInfo.findAreaByName(areaName);
        areaName = End_ComboBox.getSelectedItem().toString();
        int endAreaId = BusStopInfo.findAreaByName(areaName);
        int[] startBusStops = BusStopInfo.getBusStopsInArea(startAreaId);
        int[] endBusStops = BusStopInfo.getBusStopsInArea(endAreaId);

        for(int i=0; i< startBusStops.length; i++)
        {
            StartStop_ComboBox.addItem(BusStopInfo.getFullName(startBusStops[i]));
        }

        for(int i=0; i< endBusStops.length; i++)
        {
            endStop_ComboBox.addItem(BusStopInfo.getFullName(endBusStops[i]));
        }
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PassengerToolsGUI().setVisible(true);


                
            }
        });
    }
    private boolean created = false;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox End_ComboBox;
    private javax.swing.JComboBox StartArea_ComboBox;
    private javax.swing.JComboBox StartStop_ComboBox;
    private javax.swing.JComboBox endStop_ComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
